### ISSUE TITLE
would this not just spoof byond membership entirely?

### ISSUE THREAD

**Issue by Iamgoofball** [Redict/ByondNoAD#1]
see title

**Comment by Redict** [comment]
It is already, but only for Dream Seeker, don't know does it sending on server or it is like localy

**Comment by Iamgoofball** [comment]
I'll check

**Comment by Redict** [comment]
Checked this out, actually server requesting my Byond Membership by HTTP protocol, so whatever it is changed on my client it won't affect on server. Closing issue, if you will have any questions, open it again
